version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: votes
    networks:
      - my_network

networks:
  my_network:
